[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
# cubik_v2 = "CSgKQkUfuv8YVMiU9j3p34zSDexFHmXjFLxaDvf7KCz7"
cubik_v2 = "3s9zZaosL6hJFeDToXDoPN4sQgyVwLEdqzaztZXj1Nnk"

# [programs.devnet]
# # cubik_v2 = "3s9zZaosL6hJFeDToXDoPN4sQgyVwLEdqzaztZXj1Nnk"
# cubik_v2 = "4GgcGdn4mVtudPoX3a4xYv62ed4GKbuqn1AcxU5tU4SD"


[test.validator]
[[test.genesis]]
address = "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf"
program = "./tests/other/squads.so"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "/Users/sahilpabale/wallets/cubik/CBKiBsr31UR58LqdMWtWkKiPAsB4VAhWgWmW4XCicj3p.json"
wallet = '/Users/dhruvraj/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
lint = "yarn prettify:fix && cargo fmt"
