[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cubik_v2 = "CSgKQkUfuv8YVMiU9j3p34zSDexFHmXjFLxaDvf7KCz7"

[programs.devnet]
cubik_v2 = "CSgKQkUfuv8YVMiU9j3p34zSDexFHmXjFLxaDvf7KCz7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhruvraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
